// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiXpaMpaIlevpQ1X66dGYVQI5PdGmKA3U',
    appId: '1:180136145913:web:8873ab0ef1eb0801f40328',
    messagingSenderId: '180136145913',
    projectId: 'flash-chat-83f7d',
    authDomain: 'flash-chat-83f7d.firebaseapp.com',
    storageBucket: 'flash-chat-83f7d.firebasestorage.app',
    measurementId: 'G-4R294BHCGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDovbz2ECC53HXjNh0PfTQB2Tza-LYxLKo',
    appId: '1:180136145913:android:f8110473032d43f2f40328',
    messagingSenderId: '180136145913',
    projectId: 'flash-chat-83f7d',
    storageBucket: 'flash-chat-83f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTQ72q6bBortOTGtaZnUvXgUyx1ssdvZs',
    appId: '1:180136145913:ios:b9c76b51b47de964f40328',
    messagingSenderId: '180136145913',
    projectId: 'flash-chat-83f7d',
    storageBucket: 'flash-chat-83f7d.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTQ72q6bBortOTGtaZnUvXgUyx1ssdvZs',
    appId: '1:180136145913:ios:b9c76b51b47de964f40328',
    messagingSenderId: '180136145913',
    projectId: 'flash-chat-83f7d',
    storageBucket: 'flash-chat-83f7d.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiXpaMpaIlevpQ1X66dGYVQI5PdGmKA3U',
    appId: '1:180136145913:web:e84d5ef12ed26b02f40328',
    messagingSenderId: '180136145913',
    projectId: 'flash-chat-83f7d',
    authDomain: 'flash-chat-83f7d.firebaseapp.com',
    storageBucket: 'flash-chat-83f7d.firebasestorage.app',
    measurementId: 'G-HWFJEP14ZG',
  );

}